#!/usr/bin/env python3

import json
import os

from pipeline.stages.story_generation import StoryGenerationStage
from pipeline.llm_provider import LLMProvider
from pipeline.logger import setup_advanced_logging, get_logger

def main():
    # Setup logging first
    setup_advanced_logging()
    logger = get_logger(__name__)
    
    logger.info("=" * 60)
    logger.info("Testing Story Generation Stage")
    logger.info("=" * 60)

    input_file = 'output/news_test.json'
    output_file = 'output/stories_test.json'

    # 1. Read story ideas from the output of the previous stage
    try:
        with open(input_file, 'r', encoding='utf-8') as f:
            story_ideas = json.load(f)
        logger.info(f"Successfully loaded {len(story_ideas)} story ideas from {input_file}")
    except FileNotFoundError:
        logger.error(f"Input file not found: {input_file}")
        logger.error("Please run test_news.py first to generate the input for this stage.")
        return
    except json.JSONDecodeError:
        logger.error(f"Failed to decode JSON from {input_file}. The file might be corrupted or empty.")
        return

    if not story_ideas:
        logger.warning("Input file contains no story ideas. Nothing to process.")
        return

    # 2. Instantiate and run the StoryGenerationStage
    # Using default grammar group 0 for now
    config = {
        "llm_model_name": "gemini-2.5-flash",
        "grammar_group": 0
    }
    llm_provider = LLMProvider()
    stage = StoryGenerationStage(config=config, llm_provider=llm_provider)
    generated_stories = stage.process(story_ideas)
    
    # 3. Save the results
    output_dir = 'output'
    os.makedirs(output_dir, exist_ok=True)
    
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(generated_stories, f, ensure_ascii=False, indent=2)
    
    logger.info("Test completed!")
    logger.info(f"Results saved to: {output_file}")
    
    # 4. Log a summary
    if generated_stories:
        logger.info("Summary of generated stories:")
        for story in generated_stories:
            title_en = story.get('title', '[No Title]')
            title_ja = story.get('title_ja', '[No JA Title]')
            story_breakdown = story.get('story_breakdown', [])
            num_sentences = len(story_breakdown)
            logger.info(f"  - Title: {title_en} / {title_ja} ({num_sentences} sentences)")
            if story_breakdown:
                first_sentence_ja = story_breakdown[0].get('sentence_ja', '')
                first_sentence_en = story_breakdown[0].get('sentence_en', '')
                logger.info(f"    JA: {first_sentence_ja[:50]}...")
                logger.info(f"    EN: {first_sentence_en[:50]}...")
    else:
        logger.warning("No stories were generated by the stage.")

if __name__ == '__main__':
    main()
